[package]
name = "base64-serde"
version = "0.1.0"
authors = ["Marshall Pierce <marshall@mpierce.org>"]
homepage = "https://github.com/marshallpierce/base64-serde"
repository = "https://github.com/marshallpierce/base64-serde"
readme = 'README.md'
keywords = ["base64", "serde"]
categories = ["encoding"]
license-file = "LICENSE.txt"

[dependencies]
base64 = "0.6.0"
serde = "1.0.15"

[dev-dependencies]
serde_derive = "1.0.15"
serde_json = "1.0.3"
