[package]
name = "base64-serde"
version = "0.1.0"
authors = ["Marshall Pierce <marshall@mpierce.org>"]

[dependencies]
base64 = "0.6.0"
serde = "1.0.15"

[dev-dependencies]
serde_derive = "1.0.15"
serde_json = "1.0.3"
